export default {
    auth: {
        loginSuccess: "登录成功~",
        registSuccess: "注册成功~请进入注册邮箱激活",
        registError: "注册失败",
        wrongVerifyCode: "验证码错误",
        phoneCanNotBeChinese: "用户名不能为中文",
        phoneError: "不存在此用户",
        passwdError: "密码错误,请重试",
        unauth: "登录已失效,请重新登录",
        wrongAuth: "权限不足"
    },
    verifyCode: {
        sendSuccess: "验证码发送成功",
        wrongEmail: "邮箱格式错误",
        sendError: "验证码发送失败",
    },
    exam: {
        wrongExamPassword: "考试密码输入错误",
        joinExamSuccess: "加入考试成功",
        passedExamTime: "考试超时",
        getExamFail: "获取考试信息失败",
        submitSuccess: "提交成功",
        submitFail: "提交失败",
    },
    operation: {
        addSuccess: "添加成功",
        addFail: "添加失败",
        getListFail: "获取列表失败",
        deleteSuccess: "已删除",
        deleteFail: "删除失败,请重试",
        copyUrlSuccess: "已复制到剪贴板",
        recommendSuccess: "推荐成功",
        deleteRecommendSuccess: "已取消推荐",
        addCarouselSuccess: "轮播成功",
        deleteCarouselSuccess: "已取消轮播",
        categoryHasExist: "该分类已存在,请重试",
        updateSuccess: "已更新",
        updateFail: "更新失败",
        publishSuccess: "已发布",
        publishFail: "发布失败",
        videoInvalid: "请先预览, 确认视频可用",
        titleCannotBeEmpty: "标题不能为空,请检查后重试",
        videoUrlCannotBeEmpty: "视频地址不能为空,请检查后重试",
        relateFail: "关联失败",
        pdfEmpty:"上传资料不能为空，请检查后重试",
        authorCannotBeEmpty:"作者不能为空,请检查后重试",
        timeCannotBeEmpty:"开始时间不能为空,请检查后重试",
    }
};
